# Generated by Django 2.1.1 on 2018-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181011_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_post',
            field=models.BooleanField(default=False),
        ),
    ]
