# Generated by Django 2.1.1 on 2018-10-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default=None, max_length=380, null=True)),
                ('short_description', models.CharField(blank=True, default=None, max_length=380, null=True)),
                ('long_description', models.TextField()),
                ('remoteness', models.CharField(choices=[('0', 'Remote Friendly'), ('1', 'Remote First'), ('2', 'Remote OK'), ('3', 'Partially Remote'), ('4', 'Unknown')], default='2', max_length=2)),
                ('number_of_employees', models.CharField(choices=[('0', '1-10 people'), ('1', '1-20 people'), ('2', '1-50 people'), ('3', '100+ people'), ('2', '500+ people')], default='0', max_length=2)),
                ('headquarters', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('website', models.URLField(blank=True, default=None, null=True)),
                ('twitter', models.URLField(blank=True, default=None, null=True)),
                ('facebook', models.URLField(blank=True, default=None, null=True)),
                ('github', models.URLField(blank=True, default=None, null=True)),
                ('linkedin', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
    ]
