# Generated by Django 2.1.1 on 2018-10-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='headquarters',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='company',
            name='year_founded',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='company',
            name='long_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.CharField(choices=[('1-10 people', '1-10 people'), ('1-20 people', '1-20 people'), ('1-50 people', '1-50 people'), ('100+ people', '100+ people'), ('500+ people', '500+ people')], default='1-10 people', max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='remoteness',
            field=models.CharField(choices=[('Remote Friendly', 'Remote Friendly'), ('Remote First', 'Remote First'), ('Remote OK', 'Remote OK'), ('Partially Remote', 'Partially Remote'), ('Unknown', 'Unknown')], default='Remote OK', max_length=15),
        ),
    ]
