# Generated by Django 2.1.1 on 2018-10-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20181006_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.PositiveSmallIntegerField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
