# Generated by Django 2.1.1 on 2018-10-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20181011_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.CharField(blank=True, default=None, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, default=None, max_length=180, null=True),
        ),
    ]
