# Generated by Django 2.1.1 on 2018-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20181011_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='question_1',
            field=models.BooleanField(default=False, help_text='Is the team fully remote?'),
        ),
        migrations.AddField(
            model_name='company',
            name='question_2',
            field=models.BooleanField(default=False, help_text='Does the team get together or have a retreat?'),
        ),
        migrations.AddField(
            model_name='company',
            name='question_3',
            field=models.BooleanField(default=False, help_text='Can you work in your timezone?'),
        ),
    ]
